"""empty message

Revision ID: cee2132775e9
Revises: 9c633ac26c4a
Create Date: 2023-06-07 13:11:28.032262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee2132775e9'
down_revision = '9c633ac26c4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
